"""AI-powered findings reviewer for quality validation.

Provides skill-agnostic validation using Claude API to review findings
quality, severity appropriateness, and completeness. Single reviewer
class works across IAM, Exposure, Network, and Vulns skills.
"""

import json
import logging
from typing import Dict, Any, List, Optional
from anthropic import Anthropic

logger = logging.getLogger(__name__)


class FindingsReviewer:
    """Validate findings quality using Claude API (skill-agnostic).

    This reviewer applies to all skills (IAM, Exposure, Network, Vulns)
    without modification. It checks:
    - Severity appropriateness given evidence context
    - Missing critical findings
    - Remediation completeness
    - Evidence-severity alignment

    Cost: ~$0.02 per skill validation (1 API call)
    """

    def __init__(self, client: Anthropic):
        """Initialize reviewer with Anthropic client.

        Args:
            client: Anthropic() client for API calls
        """
        self.client = client
        self.model = "claude-opus-4-5-20251101"

    def validate(
        self,
        skill: str,
        evidence: Dict[str, Any],
        checklist: Dict[str, Any],
        findings: List[Dict[str, Any]],
        timeout: int = 60,
    ) -> Dict[str, Any]:
        """Review findings for quality, severity, and completeness.

        Args:
            skill: Skill name (iam, exposure, network, vulns)
            evidence: Raw AWS evidence collected by collector
            checklist: Security checklist for the skill
            findings: Findings generated by analyzer
            timeout: API request timeout in seconds

        Returns:
            dict: {
                "validation_status": "PASS" | "FAIL" | "NEEDS_REVIEW",
                "confidence_score": 0.0-1.0,
                "severity_mismatches": [
                    {
                        "finding_id": "IAM-001",
                        "agent_severity": "Medium",
                        "recommended_severity": "Critical",
                        "reason": "..."
                    }
                ],
                "missing_critical_findings": [
                    {
                        "check_id": "IAM-002",
                        "check_title": "...",
                        "reason": "..."
                    }
                ],
                "remediation_issues": [
                    {
                        "finding_id": "IAM-001",
                        "issue": "Remediation incomplete"
                    }
                ],
                "summary": "Human-readable validation summary",
                "recommendations": ["Suggestion 1", "Suggestion 2"]
            }

        Raises:
            ValueError: If findings or checklist format is invalid
            RuntimeError: If API call fails
        """

        logger.info(f"Starting findings review for {skill} skill")

        if not findings:
            logger.warning(f"No findings to review for {skill}")
            return {
                "validation_status": "PASS",
                "confidence_score": 1.0,
                "severity_mismatches": [],
                "missing_critical_findings": [],
                "remediation_issues": [],
                "summary": "No findings to review (clean audit)",
                "recommendations": [],
            }

        # Build prompt for Claude
        prompt = self._build_review_prompt(
            skill=skill,
            evidence=evidence,
            checklist=checklist,
            findings=findings,
        )

        try:
            logger.debug(f"Sending review request to Claude API for {skill}")
            response = self.client.messages.create(
                model=self.model,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )

            # Parse response
            review_json = response.content[0].text
            review_data = json.loads(review_json)

            logger.info(
                f"Review completed for {skill}: "
                f"status={review_data.get('validation_status')}, "
                f"confidence={review_data.get('confidence_score')}"
            )

            return review_data

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse Claude response as JSON: {e}")
            raise RuntimeError(f"Invalid JSON response from Claude: {e}")
        except Exception as e:
            logger.error(f"API error during review: {e}")
            raise RuntimeError(f"API call failed: {e}")

    def _build_review_prompt(
        self,
        skill: str,
        evidence: Dict[str, Any],
        checklist: Dict[str, Any],
        findings: List[Dict[str, Any]],
    ) -> str:
        """Build prompt for Claude reviewer.

        Args:
            skill: Skill name
            evidence: AWS evidence
            checklist: Security checklist
            findings: Current findings

        Returns:
            str: Prompt for Claude API
        """

        # Prepare evidence summary (truncate if too large)
        evidence_json = json.dumps(evidence, indent=2)
        if len(evidence_json) > 8000:
            evidence_json = evidence_json[:8000] + "\n... (truncated)"

        # Prepare checklist
        checklist_json = json.dumps(checklist, indent=2)
        if len(checklist_json) > 4000:
            checklist_json = checklist_json[:4000] + "\n... (truncated)"

        # Prepare findings
        findings_json = json.dumps(findings, indent=2)
        if len(findings_json) > 4000:
            findings_json = findings_json[:4000] + "\n... (truncated)"

        prompt = f"""You are a senior AWS security auditor reviewing findings from a junior analyst.

SKILL AUDITED: {skill.upper()}

YOUR TASK:
Review the findings below for quality, accuracy, and completeness.
Identify if severities are appropriate, missing critical findings, and remediation issues.

ORIGINAL EVIDENCE (from AWS API calls):
{evidence_json}

SECURITY CHECKLIST (all items that should be evaluated):
{checklist_json}

FINDINGS (generated by analyzer):
{findings_json}

VALIDATION CHECKLIST:
1. Are the assigned severities appropriate given the evidence?
2. Are there critical findings the analyzer missed?
3. Are remediation steps complete and actionable?
4. Does the evidence support the severity assigned?
5. Are there any findings that are incorrect or based on misinterpretation?

RESPONSE FORMAT (valid JSON):
{{
  "validation_status": "PASS" | "FAIL" | "NEEDS_REVIEW",
  "confidence_score": 0.0-1.0,
  "severity_mismatches": [
    {{
      "finding_id": "SKL-001",
      "agent_severity": "Medium",
      "recommended_severity": "Critical",
      "reason": "Clear evidence in data showing risk"
    }}
  ],
  "missing_critical_findings": [
    {{
      "check_id": "SKL-002",
      "check_title": "...",
      "reason": "Evidence clearly shows this vulnerability",
      "severity": "Critical"
    }}
  ],
  "remediation_issues": [
    {{
      "finding_id": "SKL-001",
      "issue": "Remediation is incomplete or vague"
    }}
  ],
  "summary": "Brief human-readable summary of validation results",
  "recommendations": [
    "Specific recommendation 1",
    "Specific recommendation 2"
  ]
}}

IMPORTANT:
- Return PASS only if you're confident all findings are correct and complete
- Return FAIL if there are missing critical findings or major severity errors
- Return NEEDS_REVIEW if there are minor issues or edge cases
- confidence_score: 0.0 = no confidence, 1.0 = complete confidence
- Be critical but fair - some minor issues are acceptable
"""

        return prompt

    def validate_batch(
        self,
        skills_data: List[Dict[str, Any]],
    ) -> Dict[str, Dict[str, Any]]:
        """Validate findings for multiple skills.

        Calls validator sequentially (respects API rate limits).
        Consider adding parallel calls if rate limits allow.

        Args:
            skills_data: List of dicts with keys:
                - skill: str
                - evidence: dict
                - checklist: dict
                - findings: list

        Returns:
            dict: {skill_name: validation_result} for each skill
        """

        results = {}

        for skill_data in skills_data:
            skill = skill_data["skill"]
            logger.info(f"Validating {skill} findings...")

            try:
                result = self.validate(
                    skill=skill,
                    evidence=skill_data["evidence"],
                    checklist=skill_data["checklist"],
                    findings=skill_data["findings"],
                )
                results[skill] = result
            except Exception as e:
                logger.error(f"Validation failed for {skill}: {e}")
                results[skill] = {
                    "validation_status": "ERROR",
                    "error": str(e),
                    "confidence_score": 0.0,
                }

        return results
