"""Pydantic models for correlated and pentest-enriched findings."""

from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class SourceFindingRef(BaseModel):
    """Reference to source finding that contributed to correlation."""

    id: str = Field(..., description="Source finding ID (e.g., IAM-007)")
    skill: str = Field(..., description="Skill name (iam, network, etc.)")
    title: str = Field(..., description="Finding title")
    severity: str = Field(..., description="Finding severity")
    risk_score: float = Field(..., ge=0.0, le=10.0, description="Original risk score")
    contribution_weight: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Weight in correlation (0.0-1.0)"
    )


class CorrelatedFinding(BaseModel):
    """Finding generated by correlating multiple skill findings."""

    id: str = Field(..., description="Correlation ID (CORR-XXX)")
    pattern_id: str = Field(..., description="Pattern that matched")
    severity: str = Field(..., description="Compound severity")
    compound_risk_score: float = Field(..., ge=0.0, le=10.0, description="Calculated compound risk")
    title: str = Field(..., description="Correlation title")
    description: str = Field(..., description="Detailed description of compound risk")
    attack_path: List[str] = Field(default_factory=list, description="Attack chain steps")
    source_finding_ids: List[str] = Field(..., description="IDs of source findings")
    source_findings: List[SourceFindingRef] = Field(..., description="Full source finding refs")
    affected_resources: List[str] = Field(
        default_factory=list, description="ARNs of affected resources"
    )
    remediation_priority: str = Field(
        ..., description="Remediation timeline (Immediate, High, etc.)"
    )
    remediation_steps: List[str] = Field(default_factory=list, description="Remediation actions")
    cis_reference: Optional[List[str]] = Field(default=None, description="CIS benchmark refs")
    pci_dss: Optional[List[Dict[str, str]]] = Field(default=None, description="PCI DSS controls")
    created_at: datetime = Field(default_factory=datetime.now, description="Correlation timestamp")


class CVSSScore(BaseModel):
    """CVSS v3.1 scoring breakdown for pentest findings."""

    vector_string: str = Field(..., description="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H")
    base_score: float = Field(..., ge=0.0, le=10.0)
    temporal_score: Optional[float] = Field(default=None, ge=0.0, le=10.0)
    environmental_score: Optional[float] = Field(default=None, ge=0.0, le=10.0)

    attack_vector: str
    attack_complexity: str
    privileges_required: str
    user_interaction: str
    scope: str
    confidentiality_impact: str
    integrity_impact: str
    availability_impact: str

    exploit_code_maturity: Optional[str] = None
    remediation_level: Optional[str] = None
    report_confidence: Optional[str] = None


class ThreatContext(BaseModel):
    """Threat-intelligence and ATT&CK context."""

    mitre_attack_tactics: List[str] = Field(default_factory=list)
    mitre_attack_techniques: List[str] = Field(default_factory=list)
    threat_actors: List[str] = Field(default_factory=list)
    observed_in_wild: bool = False
    exploit_maturity: str = "Not Defined"


class ExploitabilityInfo(BaseModel):
    """Exploitation walkthrough and PoC metadata."""

    exploitation_steps: List[str] = Field(default_factory=list)
    proof_of_concept: Optional[str] = None
    prerequisites: List[str] = Field(default_factory=list)
    tools_required: List[str] = Field(default_factory=list)
    exploitation_complexity: str = "Medium"
    estimated_time_to_compromise: Optional[str] = None


