"""Pydantic models for correlated findings."""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class SourceFindingRef(BaseModel):
    """Reference to source finding that contributed to correlation."""
    id: str = Field(..., description="Source finding ID (e.g., IAM-007)")
    skill: str = Field(..., description="Skill name (iam, network, etc.)")
    title: str = Field(..., description="Finding title")
    severity: str = Field(..., description="Finding severity")
    risk_score: float = Field(..., ge=0.0, le=10.0, description="Original risk score")
    contribution_weight: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Weight in correlation (0.0-1.0)"
    )


class CorrelatedFinding(BaseModel):
    """Finding generated by correlating multiple skill findings."""
    id: str = Field(..., description="Correlation ID (CORR-XXX)")
    pattern_id: str = Field(..., description="Pattern that matched")
    severity: str = Field(..., description="Compound severity")
    compound_risk_score: float = Field(..., ge=0.0, le=10.0, description="Calculated compound risk")
    title: str = Field(..., description="Correlation title")
    description: str = Field(..., description="Detailed description of compound risk")
    attack_path: List[str] = Field(default_factory=list, description="Attack chain steps")
    source_finding_ids: List[str] = Field(..., description="IDs of source findings")
    source_findings: List[SourceFindingRef] = Field(..., description="Full source finding refs")
    affected_resources: List[str] = Field(default_factory=list, description="ARNs of affected resources")
    remediation_priority: str = Field(..., description="Remediation timeline (Immediate, High, etc.)")
    remediation_steps: List[str] = Field(default_factory=list, description="Remediation actions")
    cis_reference: Optional[List[str]] = Field(default=None, description="CIS benchmark refs")
    pci_dss: Optional[List[Dict[str, str]]] = Field(default=None, description="PCI DSS controls")
    created_at: datetime = Field(default_factory=datetime.now, description="Correlation timestamp")


class CorrelationPattern(BaseModel):
    """Definition of a correlation pattern."""
    id: str = Field(..., description="Pattern identifier")
    name: str = Field(..., description="Human-readable name")
    severity: str = Field(..., description="Severity of correlated finding")
    skills_required: List[str] = Field(..., description="Skills that must be executed")
    amplification_factor: float = Field(..., ge=1.0, le=2.0, description="Risk amplification multiplier")
    title_template: str = Field(..., description="Template for correlation title")
    description_template: str = Field(..., description="Template for description")
    attack_path_steps: List[str] = Field(..., description="Attack chain steps")
    remediation_template: str = Field(..., description="Template for remediation")

    class Config:
        arbitrary_types_allowed = True  # Allow callable match_condition
